namespace NuciLog.Core
{
    using System;
    using System.Collections.Generic;

    public interface ILogger
    {
        Type SourceContext { get; }

        void SetSourceContext<T>();
        void SetSourceContext(Type type);

        void Verbose(Operation operation);
        void Verbose(Operation operation, params LogInfo[] details);
        void Verbose(Operation operation, IEnumerable<LogInfo> details);
        void Verbose(Operation operation, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Verbose(Operation operation, Exception exception);
        void Verbose(Operation operation, Exception exception, params LogInfo[] details);
        void Verbose(Operation operation, Exception exception, IEnumerable<LogInfo> details);
        void Verbose(Operation operation, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Verbose(Operation operation, OperationStatus operationStatus);
        void Verbose(Operation operation, OperationStatus operationStatus, Exception exception);
        void Verbose(Operation operation, OperationStatus operationStatus, params LogInfo[] details);
        void Verbose(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details);
        void Verbose(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Verbose(Operation operation, OperationStatus operationStatus, Exception exception, params LogInfo[] details);
        void Verbose(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details);
        void Verbose(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Verbose(string message);
        void Verbose(string message, Exception exception);
        void Verbose(Operation operation, string message);
        void Verbose(Operation operation, string message, params LogInfo[] details);
        void Verbose(Operation operation, string message, IEnumerable<LogInfo> details);
        void Verbose(Operation operation, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Verbose(Operation operation, string message, Exception exception);
        void Verbose(Operation operation, string message, Exception exception, params LogInfo[] details);
        void Verbose(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details);
        void Verbose(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Verbose(Operation operation, OperationStatus operationStatus, string message);
        void Verbose(Operation operation, OperationStatus operationStatus, string message, params LogInfo[] details);
        void Verbose(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details);
        void Verbose(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Verbose(Operation operation, OperationStatus operationStatus, string message, Exception exception);
        void Verbose(Operation operation, OperationStatus operationStatus, string message, Exception exception, params LogInfo[] details);
        void Verbose(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);

        void Debug(Operation operation);
        void Debug(Operation operation, params LogInfo[] details);
        void Debug(Operation operation, IEnumerable<LogInfo> details);
        void Debug(Operation operation, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Debug(Operation operation, Exception exception);
        void Debug(Operation operation, Exception exception, params LogInfo[] details);
        void Debug(Operation operation, Exception exception, IEnumerable<LogInfo> details);
        void Debug(Operation operation, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Debug(Operation operation, OperationStatus operationStatus);
        void Debug(Operation operation, OperationStatus operationStatus, Exception exception);
        void Debug(Operation operation, OperationStatus operationStatus, params LogInfo[] details);
        void Debug(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details);
        void Debug(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Debug(Operation operation, OperationStatus operationStatus, Exception exception, params LogInfo[] details);
        void Debug(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details);
        void Debug(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Debug(string message);
        void Debug(string message, Exception exception);
        void Debug(Operation operation, string message);
        void Debug(Operation operation, string message, params LogInfo[] details);
        void Debug(Operation operation, string message, IEnumerable<LogInfo> details);
        void Debug(Operation operation, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Debug(Operation operation, string message, Exception exception);
        void Debug(Operation operation, string message, Exception exception, params LogInfo[] details);
        void Debug(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details);
        void Debug(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Debug(Operation operation, OperationStatus operationStatus, string message);
        void Debug(Operation operation, OperationStatus operationStatus, string message, params LogInfo[] details);
        void Debug(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details);
        void Debug(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Debug(Operation operation, OperationStatus operationStatus, string message, Exception exception);
        void Debug(Operation operation, OperationStatus operationStatus, string message, Exception exception, params LogInfo[] details);
        void Debug(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details);
        void Debug(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);

        void Info(Operation operation);
        void Info(Operation operation, params LogInfo[] details);
        void Info(Operation operation, IEnumerable<LogInfo> details);
        void Info(Operation operation, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Info(Operation operation, Exception exception);
        void Info(Operation operation, Exception exception, params LogInfo[] details);
        void Info(Operation operation, Exception exception, IEnumerable<LogInfo> details);
        void Info(Operation operation, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Info(Operation operation, OperationStatus operationStatus);
        void Info(Operation operation, OperationStatus operationStatus, Exception exception);
        void Info(Operation operation, OperationStatus operationStatus, params LogInfo[] details);
        void Info(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details);
        void Info(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Info(Operation operation, OperationStatus operationStatus, Exception exception, params LogInfo[] details);
        void Info(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details);
        void Info(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Info(string message);
        void Info(string message, Exception exception);
        void Info(Operation operation, string message);
        void Info(Operation operation, string message, params LogInfo[] details);
        void Info(Operation operation, string message, IEnumerable<LogInfo> details);
        void Info(Operation operation, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Info(Operation operation, string message, Exception exception);
        void Info(Operation operation, string message, Exception exception, params LogInfo[] details);
        void Info(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details);
        void Info(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Info(Operation operation, OperationStatus operationStatus, string message);
        void Info(Operation operation, OperationStatus operationStatus, string message, params LogInfo[] details);
        void Info(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details);
        void Info(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Info(Operation operation, OperationStatus operationStatus, string message, Exception exception);
        void Info(Operation operation, OperationStatus operationStatus, string message, Exception exception, params LogInfo[] details);
        void Info(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details);
        void Info(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);

        void Warn(Operation operation);
        void Warn(Operation operation, params LogInfo[] details);
        void Warn(Operation operation, IEnumerable<LogInfo> details);
        void Warn(Operation operation, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Warn(Operation operation, Exception exception);
        void Warn(Operation operation, Exception exception, params LogInfo[] details);
        void Warn(Operation operation, Exception exception, IEnumerable<LogInfo> details);
        void Warn(Operation operation, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Warn(Operation operation, OperationStatus operationStatus);
        void Warn(Operation operation, OperationStatus operationStatus, Exception exception);
        void Warn(Operation operation, OperationStatus operationStatus, params LogInfo[] details);
        void Warn(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details);
        void Warn(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Warn(Operation operation, OperationStatus operationStatus, Exception exception, params LogInfo[] details);
        void Warn(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details);
        void Warn(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Warn(string message);
        void Warn(string message, Exception exception);
        void Warn(Operation operation, string message);
        void Warn(Operation operation, string message, params LogInfo[] details);
        void Warn(Operation operation, string message, IEnumerable<LogInfo> details);
        void Warn(Operation operation, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Warn(Operation operation, string message, Exception exception);
        void Warn(Operation operation, string message, Exception exception, params LogInfo[] details);
        void Warn(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details);
        void Warn(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Warn(Operation operation, OperationStatus operationStatus, string message);
        void Warn(Operation operation, OperationStatus operationStatus, string message, params LogInfo[] details);
        void Warn(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details);
        void Warn(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Warn(Operation operation, OperationStatus operationStatus, string message, Exception exception);
        void Warn(Operation operation, OperationStatus operationStatus, string message, Exception exception, params LogInfo[] details);
        void Warn(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details);
        void Warn(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);

        void Error(Operation operation);
        void Error(Operation operation, params LogInfo[] details);
        void Error(Operation operation, IEnumerable<LogInfo> details);
        void Error(Operation operation, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Error(Operation operation, Exception exception);
        void Error(Operation operation, Exception exception, params LogInfo[] details);
        void Error(Operation operation, Exception exception, IEnumerable<LogInfo> details);
        void Error(Operation operation, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Error(Operation operation, OperationStatus operationStatus);
        void Error(Operation operation, OperationStatus operationStatus, Exception exception);
        void Error(Operation operation, OperationStatus operationStatus, params LogInfo[] details);
        void Error(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details);
        void Error(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Error(Operation operation, OperationStatus operationStatus, Exception exception, params LogInfo[] details);
        void Error(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details);
        void Error(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Error(string message);
        void Error(string message, Exception exception);
        void Error(Operation operation, string message);
        void Error(Operation operation, string message, params LogInfo[] details);
        void Error(Operation operation, string message, IEnumerable<LogInfo> details);
        void Error(Operation operation, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Error(Operation operation, string message, Exception exception);
        void Error(Operation operation, string message, Exception exception, params LogInfo[] details);
        void Error(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details);
        void Error(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Error(Operation operation, OperationStatus operationStatus, string message);
        void Error(Operation operation, OperationStatus operationStatus, string message, params LogInfo[] details);
        void Error(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details);
        void Error(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Error(Operation operation, OperationStatus operationStatus, string message, Exception exception);
        void Error(Operation operation, OperationStatus operationStatus, string message, Exception exception, params LogInfo[] details);
        void Error(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details);
        void Error(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);

        void Fatal(Operation operation);
        void Fatal(Operation operation, params LogInfo[] details);
        void Fatal(Operation operation, IEnumerable<LogInfo> details);
        void Fatal(Operation operation, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Fatal(Operation operation, Exception exception);
        void Fatal(Operation operation, Exception exception, params LogInfo[] details);
        void Fatal(Operation operation, Exception exception, IEnumerable<LogInfo> details);
        void Fatal(Operation operation, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Fatal(Operation operation, OperationStatus operationStatus);
        void Fatal(Operation operation, OperationStatus operationStatus, Exception exception);
        void Fatal(Operation operation, OperationStatus operationStatus, params LogInfo[] details);
        void Fatal(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details);
        void Fatal(Operation operation, OperationStatus operationStatus, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Fatal(Operation operation, OperationStatus operationStatus, Exception exception, params LogInfo[] details);
        void Fatal(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details);
        void Fatal(Operation operation, OperationStatus operationStatus, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Fatal(string message);
        void Fatal(string message, Exception exception);
        void Fatal(Operation operation, string message);
        void Fatal(Operation operation, string message, params LogInfo[] details);
        void Fatal(Operation operation, string message, IEnumerable<LogInfo> details);
        void Fatal(Operation operation, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Fatal(Operation operation, string message, Exception exception);
        void Fatal(Operation operation, string message, Exception exception, params LogInfo[] details);
        void Fatal(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details);
        void Fatal(Operation operation, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Fatal(Operation operation, OperationStatus operationStatus, string message);
        void Fatal(Operation operation, OperationStatus operationStatus, string message, params LogInfo[] details);
        void Fatal(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details);
        void Fatal(Operation operation, OperationStatus operationStatus, string message, IEnumerable<LogInfo> details, params LogInfo[] details2);
        void Fatal(Operation operation, OperationStatus operationStatus, string message, Exception exception);
        void Fatal(Operation operation, OperationStatus operationStatus, string message, Exception exception, params LogInfo[] details);
        void Fatal(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details);
        void Fatal(Operation operation, OperationStatus operationStatus, string message, Exception exception, IEnumerable<LogInfo> details, params LogInfo[] details2);
    }
}
